"""Additionnal columns to dockerized_challenge

Revision ID: 0f1a9f47a75e
Revises: a49ad66aa0f1
Create Date: 2025-06-04 15:08:24.427015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f1a9f47a75e'
down_revision = 'c1b1d46b9b81'
branch_labels = None
depends_on = None


def upgrade(op):
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dockerized_challenge', sa.Column('container', sa.String(length=64), nullable=True))
    op.add_column('dockerized_challenge', sa.Column('image', sa.String(length=32), nullable=True))
    op.add_column('dockerized_challenge', sa.Column('is_running', sa.Boolean(), nullable=True))
    op.add_column('dockerized_challenge', sa.Column('port', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade(op):
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dockerized_challenge', 'port')
    op.drop_column('dockerized_challenge', 'is_running')
    op.drop_column('dockerized_challenge', 'image')
    op.drop_column('dockerized_challenge', 'container')
    # ### end Alembic commands ###
