"""add_protocol_colums_to_dockerized_challenges

Revision ID: c02ea798b874
Revises: 0f1a9f47a75e
Create Date: 2025-07-24 12:46:22.687142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c02ea798b874'
down_revision = '0f1a9f47a75e'
branch_labels = None
depends_on = None


def upgrade(op):
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dockerized_challenge', sa.Column('protocol', sa.String(length=16), nullable=True, server_default='http'))
    # ### end Alembic commands ###


def downgrade(op):
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dockerized_challenge', 'protocol')
    # ### end Alembic commands ###
