"""added_tables_for_dockerized_challenges

Revision ID: c1b1d46b9b81
Create Date: 2025-05-05 14:00:42.309278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1b1d46b9b81'
down_revision = None
branch_labels = None
depends_on = None


def upgrade(op):
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dockerized_challenge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_dynamic', sa.Boolean(), nullable=True),
    sa.Column('initial', sa.Integer(), nullable=True),
    sa.Column('minimum', sa.Integer(), nullable=True),
    sa.Column('decay', sa.Integer(), nullable=True),
    sa.Column('function', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['challenges.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade(op):
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dockerized_challenge')
    # ### end Alembic commands ###
